#网关路由配置
spring.cloud.gateway:
  discovery.locator.enabled: true
  routes:
    -   id: web-api-route
        uri: lb://web-middle-api
        predicates:
          -   Path=/middle/**
        filters:
          -   StripPrefix=1
    -   id: mini-app-route
        uri: lb://mini-app-api
        predicates:
          -   Path=/mini-app/**
        filters:
          -   StripPrefix=1
